[build]
  command = "yarn vite build"
  publish = "dist"
  [build.environment]
    NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
  from = "/pocket/*"
  to = "https://getpocket.com/v3/:splat"
  status = 200
[[redirects]]
  from = "https://pensive-wescoff-20a65f.netlify.app/*"
  to = "https://biscuits.feelmy.net/:splat"
